Add Destructure.AsDictionary<T>()
serilog/serilog pull request #1906
Opened 2023-05-07 07:57 UTC by sungam3r

fixes #1562

2023-05-07 07:59 UTC, sungam3r commented
@nblumhardt If OK could you add a note about this here https://github.com/serilog/serilog/wiki/Structured-Data#collections ?

2023-05-21 20:15 UTC, sungam3r commented
Will it be included in v3 release?

2023-05-22 00:36 UTC, nblumhardt requested changes
LGTM! I think we can get this into 3.0. Just had one suggestion for XDOC phrasing.

2023-05-22 00:36 UTC, nblumhardt commented on src/Serilog/Configuration/LoggerDestructuringConfiguration.cs
> +    /// When destructuring objects, allows to destructure inheritors of dictionaries.
How about:

> Capture instances of the specified type as dictionaries. By default, only concrete instantiations of <see cref="System.Collections.Generic.Dictionary{TKey,TValue}" /> are considered dictionary-like.

?

2023-05-23 18:08 UTC, sungam3r commented on src/Serilog/Configuration/LoggerDestructuringConfiguration.cs
> +    /// When destructuring objects, allows to destructure inheritors of dictionaries.
done

2023-05-24 21:08 UTC, nblumhardt commented
:+1:

2023-05-24 21:08 UTC, merged